#!/usr/bin/env python3
"""
Project Initializer - Creates init.sh, claude-progress.txt, and features.json template

Usage:
    init_project.py --tech-stack <stack> --project-name <name> [--output-dir <dir>]

Examples:
    init_project.py --tech-stack nodejs --project-name my-app
    init_project.py --tech-stack python --project-name api-server --output-dir ./
    init_project.py --tech-stack go --project-name service
"""

import argparse
import json
import os
from datetime import datetime
from pathlib import Path


# Tech stack templates for init.sh
INIT_TEMPLATES = {
    "nodejs": """#!/bin/bash
# Auto-generated by spec2impl initializer
# Project: {project_name}

set -e

case "$1" in
    start)
        echo "Starting development server..."
        npm run dev
        ;;
    test)
        echo "Running tests..."
        npm test
        ;;
    build)
        echo "Building project..."
        npm run build
        ;;
    lint)
        echo "Running linter..."
        npm run lint
        ;;
    *)
        echo "Usage: ./init.sh {{start|test|build|lint}}"
        echo ""
        echo "Commands:"
        echo "  start  - Start development server"
        echo "  test   - Run tests"
        echo "  build  - Build for production"
        echo "  lint   - Run linter"
        exit 1
        ;;
esac
""",
    "nextjs": """#!/bin/bash
# Auto-generated by spec2impl initializer
# Project: {project_name}

set -e

case "$1" in
    start)
        echo "Starting Next.js development server..."
        npm run dev
        ;;
    test)
        echo "Running tests..."
        npm test
        ;;
    build)
        echo "Building Next.js project..."
        npm run build
        ;;
    lint)
        echo "Running linter..."
        npm run lint
        ;;
    db)
        echo "Running database migrations..."
        npx prisma migrate dev
        ;;
    studio)
        echo "Opening Prisma Studio..."
        npx prisma studio
        ;;
    *)
        echo "Usage: ./init.sh {{start|test|build|lint|db|studio}}"
        echo ""
        echo "Commands:"
        echo "  start   - Start Next.js dev server"
        echo "  test    - Run tests"
        echo "  build   - Build for production"
        echo "  lint    - Run linter"
        echo "  db      - Run database migrations"
        echo "  studio  - Open Prisma Studio"
        exit 1
        ;;
esac
""",
    "python": """#!/bin/bash
# Auto-generated by spec2impl initializer
# Project: {project_name}

set -e

# Activate virtual environment if exists
if [ -d "venv" ]; then
    source venv/bin/activate
elif [ -d ".venv" ]; then
    source .venv/bin/activate
fi

case "$1" in
    start)
        echo "Starting development server..."
        if [ -f "manage.py" ]; then
            python manage.py runserver
        elif [ -f "app.py" ] || [ -f "main.py" ]; then
            uvicorn main:app --reload
        else
            python -m flask run --reload
        fi
        ;;
    test)
        echo "Running tests..."
        pytest
        ;;
    lint)
        echo "Running linter..."
        ruff check .
        ;;
    format)
        echo "Formatting code..."
        ruff format .
        ;;
    migrate)
        echo "Running migrations..."
        if [ -f "manage.py" ]; then
            python manage.py migrate
        else
            alembic upgrade head
        fi
        ;;
    *)
        echo "Usage: ./init.sh {{start|test|lint|format|migrate}}"
        echo ""
        echo "Commands:"
        echo "  start   - Start development server"
        echo "  test    - Run tests with pytest"
        echo "  lint    - Run ruff linter"
        echo "  format  - Format code with ruff"
        echo "  migrate - Run database migrations"
        exit 1
        ;;
esac
""",
    "go": """#!/bin/bash
# Auto-generated by spec2impl initializer
# Project: {project_name}

set -e

case "$1" in
    start)
        echo "Starting Go server..."
        go run .
        ;;
    test)
        echo "Running tests..."
        go test ./...
        ;;
    build)
        echo "Building binary..."
        go build -o bin/{project_name} .
        ;;
    lint)
        echo "Running linter..."
        golangci-lint run
        ;;
    *)
        echo "Usage: ./init.sh {{start|test|build|lint}}"
        echo ""
        echo "Commands:"
        echo "  start  - Start development server"
        echo "  test   - Run tests"
        echo "  build  - Build binary"
        echo "  lint   - Run golangci-lint"
        exit 1
        ;;
esac
""",
    "rust": """#!/bin/bash
# Auto-generated by spec2impl initializer
# Project: {project_name}

set -e

case "$1" in
    start)
        echo "Starting Rust server..."
        cargo run
        ;;
    test)
        echo "Running tests..."
        cargo test
        ;;
    build)
        echo "Building release..."
        cargo build --release
        ;;
    lint)
        echo "Running clippy..."
        cargo clippy
        ;;
    fmt)
        echo "Formatting code..."
        cargo fmt
        ;;
    *)
        echo "Usage: ./init.sh {{start|test|build|lint|fmt}}"
        echo ""
        echo "Commands:"
        echo "  start  - Start development server"
        echo "  test   - Run tests"
        echo "  build  - Build release binary"
        echo "  lint   - Run clippy linter"
        echo "  fmt    - Format code"
        exit 1
        ;;
esac
""",
    "generic": """#!/bin/bash
# Auto-generated by spec2impl initializer
# Project: {project_name}

set -e

case "$1" in
    start)
        echo "Starting development server..."
        # TODO: Add your start command here
        ;;
    test)
        echo "Running tests..."
        # TODO: Add your test command here
        ;;
    build)
        echo "Building project..."
        # TODO: Add your build command here
        ;;
    *)
        echo "Usage: ./init.sh {{start|test|build}}"
        echo ""
        echo "Commands:"
        echo "  start  - Start development server"
        echo "  test   - Run tests"
        echo "  build  - Build project"
        exit 1
        ;;
esac
"""
}

PROGRESS_TEMPLATE = """# Claude Progress Log
# Project: {project_name}
# Generated: {date}
# Tech Stack: {tech_stack}

================================================================================
## Current Session
================================================================================

Started:
Current Task:
Status:

--------------------------------------------------------------------------------
### Working Notes

(Add notes as you work)

================================================================================
## Completed Tasks
================================================================================

(none yet)

================================================================================
## Blocked / Needs Attention
================================================================================

(none yet)

================================================================================
## Session History
================================================================================

### Session 1 - {date}
- Started:
- Completed:
- Notes:

"""

FEATURES_TEMPLATE = {
    "project": {
        "name": "",
        "generatedAt": "",
        "techStack": []
    },
    "features": [
        {
            "id": "F-001",
            "name": "Example Feature",
            "description": "Replace with actual feature description",
            "status": "pending",
            "priority": "high",
            "tasks": [],
            "dependencies": [],
            "notes": ""
        }
    ],
    "summary": {
        "total": 1,
        "pending": 1,
        "in_progress": 0,
        "completed": 0,
        "failed": 0
    }
}


def get_init_template(tech_stack: str) -> str:
    """Get the init.sh template for the given tech stack."""
    # Normalize tech stack name
    stack_lower = tech_stack.lower()

    # Map common variations
    stack_mapping = {
        "node": "nodejs",
        "node.js": "nodejs",
        "javascript": "nodejs",
        "typescript": "nodejs",
        "next": "nextjs",
        "next.js": "nextjs",
        "py": "python",
        "django": "python",
        "fastapi": "python",
        "flask": "python",
        "golang": "go",
        "rs": "rust",
    }

    normalized = stack_mapping.get(stack_lower, stack_lower)
    return INIT_TEMPLATES.get(normalized, INIT_TEMPLATES["generic"])


def create_init_sh(project_name: str, tech_stack: str, output_dir: Path) -> Path:
    """Create init.sh file."""
    template = get_init_template(tech_stack)
    content = template.format(project_name=project_name)

    init_path = output_dir / "init.sh"
    init_path.write_text(content)
    init_path.chmod(0o755)

    return init_path


def create_progress_log(project_name: str, tech_stack: str, output_dir: Path) -> Path:
    """Create claude-progress.txt file."""
    date = datetime.now().strftime("%Y-%m-%d")
    content = PROGRESS_TEMPLATE.format(
        project_name=project_name,
        tech_stack=tech_stack,
        date=date
    )

    progress_path = output_dir / "claude-progress.txt"
    progress_path.write_text(content)

    return progress_path


def create_features_json(project_name: str, tech_stack: str, output_dir: Path) -> Path:
    """Create docs/features.json template file."""
    # Ensure docs directory exists
    docs_dir = output_dir / "docs"
    docs_dir.mkdir(exist_ok=True)

    features = FEATURES_TEMPLATE.copy()
    features["project"] = {
        "name": project_name,
        "generatedAt": datetime.now().isoformat(),
        "techStack": [tech_stack] if tech_stack else []
    }

    features_path = docs_dir / "features.json"
    features_path.write_text(json.dumps(features, indent=2))

    return features_path


def main():
    parser = argparse.ArgumentParser(
        description="Initialize project with init.sh, claude-progress.txt, and features.json"
    )
    parser.add_argument(
        "--tech-stack",
        required=True,
        help="Tech stack (nodejs, nextjs, python, go, rust, generic)"
    )
    parser.add_argument(
        "--project-name",
        required=True,
        help="Project name"
    )
    parser.add_argument(
        "--output-dir",
        default=".",
        help="Output directory (default: current directory)"
    )

    args = parser.parse_args()

    output_dir = Path(args.output_dir).resolve()

    print(f"Initializing project: {args.project_name}")
    print(f"Tech stack: {args.tech_stack}")
    print(f"Output directory: {output_dir}")
    print()

    # Create files
    init_path = create_init_sh(args.project_name, args.tech_stack, output_dir)
    print(f"Created: {init_path}")

    progress_path = create_progress_log(args.project_name, args.tech_stack, output_dir)
    print(f"Created: {progress_path}")

    features_path = create_features_json(args.project_name, args.tech_stack, output_dir)
    print(f"Created: {features_path}")

    print()
    print("Initialization complete!")
    print()
    print("Next steps:")
    print("1. Edit docs/features.json to add your project features")
    print("2. Run ./init.sh start to start the development server")
    print("3. Update claude-progress.txt as you work")


if __name__ == "__main__":
    main()
